WebApplication2.0/Controllers/KoppelController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Web_Applicatie.Models;


namespace Web_Applicatie.Controllers
{
    public class KoppelController : Controller
    {
        // GET: Koppel
        public ViewResult Start()
        {

            var viewResult = new ViewResult();
            return View(GetSoftwareLijst());
        }

        public IEnumerable<Software> GetSoftwareLijst()
        {
            var softwareLijst = new List<Software>
            {
                new Software { Naam = "Exact", Description = "Exact is een onderneming die software ontwikkelt gericht op de ondersteuning van met name het midden- en kleinbedrijf. Het bedrijf vindt zijn oorsprong in Exact Software, een Nederlands softwarebedrijf dat is opgericht in 1984." },
                new Software { Naam = "SnelStart", Description = "SnelStart is een van de eerste boekhoud- en facturatiepakketten in Nederland. Sinds begin jaren tachtig ontwikkelen wij boekhoudsoftware voor ondernemers. Al die jaren was de insteek om boekhouden eenvoudig en begrijpelijk te maken voor elke ondernemer. Het is dan ook geen wonder dat het aantal gebruikers van onze software na ruim 35 jaar nog steeds groeit." }
            };

            return softwareLijst;
        }
    }
}

WebApplication2.0/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Kats Productions</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
	<nav class="navbar navbar-fixed-top">
		<div class="container">
			<div class="navbar-header">
				<button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
				</button>
				@Html.ActionLink("Web Applicatie 2.0", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
			</div>
			<div class="navbar-nav id=" navbarSupportedContent"">
				<ul class="nav navbar-nav">
					<li class="nav-item">@Html.ActionLink("Home", "Index", "Home")</li>
					<li class="nav-item">@Html.ActionLink("About", "About", "Home")</li>
					<li class="nav-item">@Html.ActionLink("Koppelingen", "Start", "Koppel")</li>
				</ul>
			</div>
			<div class="nav navbar-nav navbar-right">
				<ul class="nav navbar-nav">
					<li class="nav-item">
						<a href="Register">Register</a>
					</li>
					<li class="nav-item">
						<a href="Register">LogOut</a>
					</li>
				</ul>
			</div>
		</div>
	</nav>


	<div class="container body-content">
		@RenderBody()
		<hr />
		<footer>
			<p>&copy; @DateTime.Now.Year - Kats Productions</p>
		</footer>
	</div>

	@Scripts.Render("~/bundles/jquery")
	@Scripts.Render("~/bundles/bootstrap")
	@RenderSection("scripts", required: false)
</body>
</html>